vllm:
  model: "HPAI-BSC/Llama3-Aloe-8B-Alpha"
  tokenizer_mode:
  trust_remote_code:
  tensor_parallel_size:
  dtype:
  quantization:
  revision:
  tokenizer_revision:
  seed:
  gpu_memory_utilization:
  swap_space:
  enforce_eager:
  max_context_len_to_capture:
  disable_custom_all_reduce:
  max_model_len:

config:
  dataset: "mmlu"
  subject: "all"
  overwrite: True
  type: "medprompt"
  vector_database: "chromadb"
  embedding: "Salesforce/SFR-Embedding-Mistral"
  k: 5
  ensembles: 5
  shuffle: True
  database: "database_medmcqa_reduced"

sampling_params:
  n:
  best_of:
  presence_penalty:
  frequency_penalty:
  repetition_penalty:
  temperature:
  top_p:
  top_k:
  min_p:
  seed:
  use_beam_search:
  length_penalty:
  early_stopping:
  stop: ["<|im_end|>", "<|im_start|>", "[INST]", "[/INST]", "<s>", "</s>", "<|eot_id|>", "<|start_header_id|>"]
  stop_token_ids:
  include_stop_str_in_output:
  ignore_eos:
  max_tokens: 1000
  logprobs:
  prompt_logprobs:
  skip_special_tokens:
  spaces_between_special_tokens:
  logits_processors: