vllm:
  model: "HPAI-BSC/Llama3-Aloe-8B-Alpha"
  tokenizer_mode:
  trust_remote_code: true
  tensor_parallel_size:
  dtype:
  quantization:
  revision:
  tokenizer_revision:
  seed: 42
  gpu_memory_utilization:
  swap_space:
  enforce_eager:
  max_context_len_to_capture:
  disable_custom_all_reduce:
  max_model_len:

config:
  dataset: "medqa_4opt"
  subject:
  overwrite: True
  type: "qa"
  reward_model: /gpfs/projects/bsc70/hpai/storage/data/heka/Models/ArmoRM-Llama3-8B-v0.1
  final_answer: reflection
  ensembles: 5
  vector_database: "chromadb"
  embedding: "Salesforce/SFR-Embedding-Mistral"
  k: 5
  database: "open_ended_medqa_database"


sampling_params:
  n:
  best_of:
  presence_penalty:
  frequency_penalty:
  repetition_penalty:
  temperature: 0.6
  top_p: 0.9
  top_k:
  min_p:
  seed:
  use_beam_search:
  length_penalty:
  early_stopping:
  stop: ["<|im_end|>", "[/INST]", "</s>", "<|eot_id|>", <|endoftext|>]
  stop_token_ids:
  include_stop_str_in_output:
  ignore_eos:
  max_tokens: 2000
  logprobs:
  prompt_logprobs:
  skip_special_tokens:
  spaces_between_special_tokens:
  logits_processors:

evaluator:
  model: meta-llama/Meta-Llama-3.1-70B-Instruct
  tokenizer_mode:
  trust_remote_code:
  tensor_parallel_size: 4
  dtype: bfloat16
  quantization:
  revision:
  tokenizer_revision:
  seed: 42
  gpu_memory_utilization: 0.8
  swap_space:
  enforce_eager:
  max_context_len_to_capture:
  disable_custom_all_reduce:
  max_model_len: 4096