vllm:
  model: microsoft/Phi-3-mini-4k-instruct
  tokenizer_mode:
  trust_remote_code: true
  tensor_parallel_size:
  dtype: float16 # Colab TPU only supports float16
  quantization:
  revision:
  tokenizer_revision:
  seed: 42
  gpu_memory_utilization: 0.75
  swap_space:
  enforce_eager:
  max_context_len_to_capture:
  disable_custom_all_reduce:
  max_model_len:

config:
  dataset: "mmlu"
  subject: "anatomy"
  overwrite: True
  type: "medprompt"
  vector_database: "chromadb"
  embedding: "NeuML/pubmedbert-base-embeddings"
  k: 5
  ensembles: 5
  shuffle: True
  database: "database_medmcqa_reduced"

sampling_params:
  n:
  best_of:
  presence_penalty:
  frequency_penalty:
  repetition_penalty:
  temperature: 0.4
  top_p:
  top_k:
  min_p:
  seed:
  use_beam_search:
  length_penalty:
  early_stopping:
  stop: ["<|im_end|>", "<|im_start|>", "[INST]", "[/INST]", "<s>", "</s>", "<|eot_id|>", "<|start_header_id|>"]
  stop_token_ids:
  include_stop_str_in_output:
  ignore_eos:
  max_tokens: 1000
  logprobs:
  prompt_logprobs:
  skip_special_tokens:
  spaces_between_special_tokens:
  logits_processors: